collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.4203441
  brandStrength: 0.3528464
  lightness: 0.8698808
  brandColors:
    - '#1F1E28'
    - '#77A3F4'
    - '#655354'
    - '#4B6DA3'
    - '#FFCEB4'
  rhythmicContrast: 0.1564505
typography_spectrum: 0.2003222
layout_spectrum: 0.2776584
name: Spero
